/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_peakchao_com_androidndk_JniUtil */

#ifndef _Included_ndk_peakchao_com_androidndk_JniUtil
#define _Included_ndk_peakchao_com_androidndk_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_peakchao_com_androidndk_JniUtil
 * Method:    getToastString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_peakchao_com_androidndk_JniUtil_getToastString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
