/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_peakchao_com_androidndk_AESUtil */

#ifndef _Included_ndk_peakchao_com_androidndk_AESUtil
#define _Included_ndk_peakchao_com_androidndk_AESUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_peakchao_com_androidndk_AESUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_peakchao_com_androidndk_AESUtil_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ndk_peakchao_com_androidndk_AESUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_peakchao_com_androidndk_AESUtil_decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
