/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil */

#ifndef _Included_ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil
#define _Included_ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil
 * Method:    Encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil_Encryption
        (JNIEnv *, jclass, jstring);

/*
 * Class:     ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil
 * Method:    Decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_peakchao_com_androidndk_EncryptionAndDecryptUtil_Decrypt
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
